#IPO e XCMS script - Elisa R. (elisarm.antunes@gmail.com)

##-------------------- Package References ----------------------##

# Websites:

# https://bioconductor.org/packages/release/bioc/html/xcms.html
# https://www.bioconductor.org/packages/release/bioc/html/IPO.html


# Citation

citation("xcms")
citation("IPO")

##-------------------- installation ----------------------##

if (!requireNamespace("BiocManager", quietly=TRUE))
        install.packages("BiocManager")

BiocManager::install("IPO") # install IPO

if (!requireNamespace("BiocManager", quietly = TRUE))
        install.packages("BiocManager")

BiocManager::install("xcms") # install xcms

if (!requireNamespace("BiocManager", quietly = TRUE))
        install.packages("BiocManager")

BiocManager::install("CAMERA") # install CAMERA.

##-------------------- files ----------------------##

datafiles <- list.files("G:/2.LABMETAMASS/DOUTORADO/DADOS/mikania/mzXML", recursive = TRUE, full.names = TRUE)
datafiles[1205:1280] # lists files names. Check if the correct files were found

# OBS: files need to be .mzxML format -  Check MSConvert from Proteowizard.

##-------------------- loading packages ----------------------##

library(xcms)
library(Rmpi)
library(CAMERA)
library (IPO)

##-------------------- IPO ----------------------##

# peak picking parameters optimization
peakpickingParameters <- getDefaultXcmsSetStartingParams('matchedFilter') #only matchedFilter (lowres)

peakpickingParameters$step <- c(0.1, 0.2)
peakpickingParameters$fwhm <- c(1, 2)
peakpickingParameters$steps <- 2

time.xcmsSet <- system.time({
        resultPeakpicking <-
                optimizeXcmsSet(files = datafiles[1205:1280],# check datafiles object. Input only the files to be tested
                                params = peakpickingParameters,
                                nSlaves = 1,# only change if your computer can handle it.
                                subdir = 'G:/2.LABMETAMASS/DOUTORADO/DADOS/mikania/IPO', #can be null if no plot is to be saved
                                plot = TRUE)
})

resultPeakpicking$best_settings$result
optimizedXcmsSetObject <- resultPeakpicking$best_settings$xset

# retention time correction optimization
# OBS: both chunks take a long time, depending on the amount of files.
# Save the R image or object (save.image() + load () | saveRDS() + readRDS()) to keep the objects stored

retcorGroupParameters <- getDefaultRetGroupStartingParams()
retcorGroupParameters$profStep <- 1
retcorGroupParameters$gapExtend <- 2.7
retcorGroupParameters$mzwid <-
time.RetGroup <- system.time({
                resultRetcorGroup <-
                        optimizeRetGroup(xset = optimizedXcmsSetObject,
                                         params = retcorGroupParameters,
                                         nSlaves = 1, #only increase if the PC can handle it
                                         subdir =  'G:/2.LABMETAMASS/DOUTORADO/DADOS/Maytenus/IPO', #can be set no NULL
                                         plot = TRUE)
        })
writeRScript(resultPeakpicking$best_settings$parameters,
             resultRetcorGroup$best_settings)

 time.xcmsSet
time.RetGroup

sessionInfo()

##-------------------- XCMS ----------------------##

# Separate the QC and other files on subdirectories - based on groups.

setwd ("G:/2.LABMETAMASS/DOUTORADO/DADOS/mikania/mzXML/xcms")

# the script generated by IPO is similar to the one below. Substitute this chunk
# with the one generated by IPO and rename the objects so they don't overwrite each other.


library(xcms)
library(Rmpi)
library(CAMERA)

xset <- xcmsSet( 
        method   = "matchedFilter",
        fwhm     = 28,
        snthresh = 3,
        step     = 0.15,
        steps    = 3,
        sigma    = 11.8906064209275,
        max      = 5,
        mzdiff   = 0.35,
        index    = FALSE)

xset2 <- retcor( 
        xset,
        method         = "obiwarp",
        plottype       = "none",
        distFunc       = "cor_opt",
        profStep       = 1,
        center         = 68,
        response       = 1,
        gapInit        = 0.2,
        gapExtend      = 2.4,
        factorDiag     = 2,
        factorGap      = 1,
        localAlignment = 0)

xset3 <- group( 
        xset2,
        method  = "density",
        bw      = 29.2,
        mzwid   = 0.015,
        minfrac = 0.2, # 0.7 standard, not finding any group 
        minsamp = 1,
        max     = 50)

xset4 <- fillPeaks(xset3)

# The IPO script ends here

# Substitute the object names inside the ( ) accordingly.

an <- xsAnnotate(xset4)

#Creation of an xsAnnotate object
anF <- groupFWHM(an, perfwhm = 0.6)

#Perfwhm = parameter defines the window width, which is used for matching
anI <- findIsotopes(anF, mzabs=0.01)


#Mzabs = the allowed m/z error
anIC <- groupCorr(anI, cor_eic_th=0.75)
anFA <- findAdducts(anIC, polarity="negative") #change polarity accordingly

write.csv(getPeaklist(anIC), file='mikaniaipo2.csv') # generates a table of features
