#IPO e XCMS script - Elisa R. (elisarm.antunes@gmail.com)

##-------------------- Package References ----------------------##

# Websites:

# https://bioconductor.org/packages/release/bioc/html/xcms.html
# https://www.bioconductor.org/packages/release/bioc/html/IPO.html


# Citation

citation("xcms")
citation("IPO")

##-------------------- installation ----------------------##

if (!requireNamespace("BiocManager", quietly=TRUE))
        install.packages("BiocManager")

BiocManager::install("IPO") # install IPO

if (!requireNamespace("BiocManager", quietly = TRUE))
        install.packages("BiocManager")

BiocManager::install("xcms") # install xcms

if (!requireNamespace("BiocManager", quietly = TRUE))
        install.packages("BiocManager")

BiocManager::install("CAMERA") # install CAMERA.

##-------------------- files ----------------------##

datafiles <- list.files("G:/2.LABMETAMASS/DOUTORADO/DADOS/maytenus/mzxml/xcms/train_test_split/output/train", recursive = TRUE, full.names = TRUE)
set.seed(2187)
ipo_data <- sample(datafiles,100)
ipo_data

# OBS: files need to be .mzxML format -  Check MSConvert from Proteowizard.

##-------------------- loading packages ----------------------##

library(xcms)
library(Rmpi)
library(CAMERA)
library (IPO)

##-------------------- IPO ----------------------##

# peak picking parameters optimization
peakpickingParameters <- getDefaultXcmsSetStartingParams('matchedFilter') #only matchedFilter (lowres)

# peakpickingParameters$step <- c(0.1, 0.2)
# peakpickingParameters$fwhm <- c(1, 2)
# peakpickingParameters$steps <- 2

time.xcmsSet <- system.time({
        resultPeakpicking <-
                optimizeXcmsSet(files = ipo_data,# check datafiles object. Input only the files to be tested
                                params = peakpickingParameters,
                                nSlaves = 1,# only change if your computer can handle it.
                                subdir = 'G:/2.LABMETAMASS/DOUTORADO/DADOS/maytenus/IPO-plots', #can be null if no plot is to be saved
                                plot = TRUE)
})

resultPeakpicking$best_settings$result
optimizedXcmsSetObject <- resultPeakpicking$best_settings$xset
save.image()

# retention time correction optimization
# OBS: both chunks take a long time, depending on the amount of files.
# Save the R image or object (save.image() + load () | saveRDS() + readRDS()) to keep the objects stored

retcorGroupParameters <- getDefaultRetGroupStartingParams()
#retcorGroupParameters$profStep <- 1
#retcorGroupParameters$gapExtend <- 2.7
#retcorGroupParameters$mzwid <-
time.RetGroup <- system.time({
                resultRetcorGroup <-
                        optimizeRetGroup(xset = optimizedXcmsSetObject,
                                         params = retcorGroupParameters,
                                         nSlaves = 1, #only increase if the PC can handle it
                                         subdir =  'G:/2.LABMETAMASS/DOUTORADO/DADOS/maytenus/IPO-plots', #can be set no NULL
                                         plot = TRUE)
        })

save.image()
writeRScript(resultPeakpicking$best_settings$parameters,
             resultRetcorGroup$best_settings)

time.xcmsSet
time.RetGroup

sessionInfo()

##-------------------- XCMS ----------------------##

# Separate the QC and other files on subdirectories - based on groups.

setwd("G:/2.LABMETAMASS/DOUTORADO/DADOS/maytenus/mzxml/xcms/train_test_split/output/train")

# the script generated by IPO is similar to the one below. Substitute this chunk
# with the one generated by IPO and rename the objects so they don't overwrite each other.


library(xcms)
library(CAMERA)
library(beepr)

# maytenus10 - 266 
# fwhm     = 18, 
# snthresh = 3, 
# step     = 1, ***
# bw       = 25
# mzdiff   = 1, 
# mzwid   = 0.1, ***
# minfrac = 0.1, 
# minsamp = 10, ****
# max     = 100) ***


xset <- xcmsSet( 
        method   = "matchedFilter",
        fwhm     = 21.5,
        snthresh = 6.5,
        step     = 0.1,
        steps    = 4,
        sigma    = 9.13028707321216,
        max      = 5,
        mzdiff   = 0.38,
        index    = FALSE)
xset2 <- retcor( 
        xset,
        method         = "obiwarp",
        plottype       = "none",
        distFunc       = "cor_opt",
        profStep       = 0.85,
        center         = 16,
        response       = 1,
        gapInit        = 0.2,
        gapExtend      = 2.4,
        factorDiag     = 2,
        factorGap      = 1,
        localAlignment = 0)
xset3 <- group( 
        xset2,
        method  = "density",
        bw      = 30,
        mzwid   = 0.015,
        minfrac = 0.7,
        minsamp = 1,
        max     = 50)

xset4 <- fillPeaks(xset3)

# The IPO script ends here

# Substitute the object names inside the ( ) accordingly.

an <- xsAnnotate(xset4)

#Creation of an xsAnnotate object
anF <- groupFWHM(an, perfwhm = 0.6)

#Perfwhm = parameter defines the window width, which is used for matching
anI <- findIsotopes(anF, mzabs=0.01)

#Mzabs = the allowed m/z error
anIC <- groupCorr(anI, cor_eic_th=0.75)
anFA <- findAdducts(anIC, polarity="negative") #change polarity accordingly

write.csv(getPeaklist(anIC), file="maytenus_train_xcms.csv") # generates a table of features

beep()


## -------------- Optimized with QCS --------------## 

# xset <- xcmsSet(
#         method   = "matchedFilter",
#         fwhm     = 18, # 30.5 # 15
#         snthresh = 3, # 9.384 
#         step     = 1, #0.095
#         steps    = 5,
#         sigma    = 12.9522677085103, # 12.9522677085103
#         max      = 5, #5 
#         mzdiff   = 1, #0.325
#         index    = FALSE)
# 
# xset2 <- retcor(
#         xset,
#         method         = "obiwarp",
#         plottype       = "none",
#         distFunc       = "cor_opt",
#         profStep       = 1, #1
#         center         = 13, #13
#         response       = 1,
#         gapInit        = 0.4,
#         gapExtend      = 2.4,
#         factorDiag     = 2,
#         factorGap      = 1,
#         localAlignment = 1) #0
# 
# xset3 <- group(
#         xset2,
#         method  = "density",
#         bw      = 25, #30
#         mzwid   = 0.1, # 0.015 - the smaller the number, less features
#         minfrac = 0.1, # 0.2
#         minsamp = 10, # 25** 
#         max     = 100) # 50 does not change shit
# 
# xset4 <- fillPeaks(xset3)


# maytenus10 - 266 

# fwhm     = 30.5, 
# snthresh = 9.384, 
# step     = 0.095, 
# steps    = 5,
# sigma    = 12.9522677085103,
# max      = 5,
# mzdiff   = 0.325, 
# index    = FALSE
# method  = "density",
# bw      = 30, 
# mzwid   = 0.015, 
# minfrac = 0.2, 
# minsamp = 25, 
# max     = 50) 

